### ISSUE TITLE
Mail should also include the sent date

### ISSUE THREAD

**Issue by rexim** [codingteam/horta-hell#360] opened 2015-12-18 05:59 UTC

**Comment by ForNeVeR** [comment] 2015-12-18 06:00
Duplicate of #144.

**Closed by ForNeVeR** 2015-12-18 06:00 UTC
Labels: enhancement

**Comment by rexim** [comment] 2015-12-18 06:04
@ForNeVeR thanks!

**Comment by ForNeVeR** [comment] 2015-12-18 06:08
:goat:

**Comment by rexim** [comment] 2015-12-18 06:49
:goat: :eyes:
