### ISSUE TITLE
Enqueues messages without confirmation

### ISSUE THREAD

**Issue by Minoru** [codingteam/horta-hell#362] opened 2016-01-04 09:58 UTC
[@rexim tried to send a message, but Horta didn't confirm it](http://0xd34df00d.me/logs/chat/codingteam@conference.jabber.ru/2016/01/04.html#09:34:08):

> &lt;rexim> send/Minoru/> Alexander added 20 books ._./
> &lt;rexim> $access
> &lt;horta hell> rexim: Администратор
> &lt;rexim> send/Minoru/> Alexander added 20 books ._./
> &lt;horta hell> rexim: Сообщение помещено в очередь.

Upon joining the conference, I received both messages.

**Comment by ForNeVeR** [comment] 2016-01-04 11:25
See https://github.com/codingteam/horta-hell/issues/361#issuecomment-168361304. Closed as duplicate of #290 and https://github.com/codingteam/xmpp.codingteam.org.ru/issues/3.

**Comment by ForNeVeR** [comment] 2016-01-04 11:26
By the way, now I'm back to the server, so Horta will feel itself much better.

**Closed by ForNeVeR** 2016-01-04 11:25 UTC
